import { PRODUCTS } from '@/lib/products';

export const SITE_URL = 'https://aralabs.com.br';
export const SITE_NAME = 'AraLabs';
export const SITE_TAGLINE = 'Tecnologia simples para pequenos negócios';
export const SITE_DESCRIPTION =
  'Software simples para pequenos negócios e apps para famílias, feitos em Arapongas (PR): Komyx para buffets, Lumo, Casa Leve e sistemas sob medida.';
export const SITE_TWITTER_DESCRIPTION = `Tecnologia simples para pequenos negócios: produtos prontos (${PRODUCTS.map((p) => p.name).join(', ')}) e sistemas sob medida. Arapongas, PR.`;
export const CONTACT_EMAIL = 'contato@aralabs.com.br';
export const JOBS_EMAIL = 'trabalhe@aralabs.com.br';
/** Digits only with country code (55...). Empty hides every WhatsApp button; email is the fallback. */
export const CONTACT_WHATSAPP = '5543988445445';
export const LOCALE = 'pt-BR';

export const ORG_ADDRESS = {
  streetAddress: 'Rua Guaraúna, 288 - Jardim Primavera',
  addressLocality: 'Arapongas',
  addressRegion: 'PR',
  postalCode: '86702-480',
  addressCountry: 'BR',
} as const;

export const LOGO_PATH = '/brand/logo-mark.png';
/** Root share image, generated by src/app/opengraph-image.tsx. */
export const DEFAULT_OG_IMAGE = '/opengraph-image';

export const LEGAL_NAME = 'Thiago Tavares Consulting Ltda. - ME';
export const CNPJ = '50.010.836/0001-45';

export const ORG_ID = `${SITE_URL}/#organization`;
export const WEBSITE_ID = `${SITE_URL}/#website`;

export function contactHref(subject: string, body?: string) {
  if (CONTACT_WHATSAPP) {
    return `https://wa.me/${CONTACT_WHATSAPP}?text=${encodeURIComponent(body ?? subject)}`;
  }
  return `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(subject)}${body ? `&body=${encodeURIComponent(body)}` : ''}`;
}
